name = "boulderjs-org"
compatibility_date = "2024-11-11"
account_id = "2c1139e40b2ed1b0a3fed3d2204af46f"

main = "./.output/server/index.mjs"
route = "boulderjs.org/*"
compatibility_flags = [ "nodejs_compat" ]

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

[site]
bucket = ".output/public"
